apiVersion: v1
kind: Service
metadata:
  name: reporting-db-headless
spec:
  selector:
    app: reporting-db
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: reporting-db
spec:
  selector:
    app: reporting-db
  ports:
  - port: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: reporting-db
  labels:
    app: reporting-db
spec:
  selector:
    matchLabels:
      app: reporting-db
  serviceName: reporting-db-headless
  replicas: 1
  template:
    metadata:
      labels:
        app: reporting-db
    spec:
      containers:
      - name: postgresql
        image: docker.io/library/postgres:13-bullseye
        env:
        - name: POSTGRES_DB
          value: reporting
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: reporting-db-superuser
              key: user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: reporting-db-superuser
              key: password
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: data
          subPath: data
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            cpu: 500m
            memory: 256Mi
          limits:
            cpu: 1500m
            memory: 1Gi
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
