# This file can be used for local tinkering
version: "3.8"
services:
  postgres:
    image: docker.io/library/postgres:14-bullseye
    environment:
      POSTGRES_DB: reporting-db
      POSTGRES_PASSWORD: reporting
      POSTGRES_USER: reporting
    ports:
      - "5432:5432"
    volumes:
      - "postgres:/var/lib/postgresql/data"
volumes:
  postgres: {}
