apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: reporting-db
spec:
  template:
    spec:
      containers:
      - name: postgresql
        image: centos/postgresql-13-centos7:latest
        env:
        - $patch: replace
        - name: POSTGRESQL_DATABASE
          value: reporting
        - name: POSTGRESQL_USER
          valueFrom:
            secretKeyRef:
              name: reporting-db-superuser
              key: user
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: reporting-db-superuser
              key: password
        volumeMounts:
        - name: data
          subPath: data
          mountPath: /var/lib/pgsql/data
